### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by SkyBulk** [Thang-Ng/mitre-attack-data#1]
it's a very interesting project!

Would you consider adding a license to this repository to specify under which terms this code can be used?

**Comment by thang-ngn** [comment]
Hi @SkyBulk, I will add the license as soon as possible.

Regards

**Comment by SkyBulk** [comment]
is possible to get some permissible license?

**Comment by thang-ngn** [comment]
Hi @SkyBulk, sorry for the late replying.

I have added a License to the repo. The data contained in this repo can be used under the Attribution-NonCommercial-ShareAlike 4.0 International license (https://creativecommons.org/licenses/by-nc-sa/4.0/)

**Comment by SkyBulk** [comment]
may I wonder if possible to make it more permissible ( apache2, isc, bsd-3 ) in order to integrate into our project by adding the credits ofc or it is possible to make a collaboration?

**Comment by thang-ngn** [comment]
I wish I could, but this project contains data from other sources which enforce us to distribute under the Attribution-NonCommercial-ShareAlike 4.0 International license.

**Comment by SkyBulk** [comment]
in this case, :/ .. is possible to get the list of the `other sources` , so maybe I can make it possible to change the licenses contacting the authors?
